create table earmarks (
  id bigint generated by default as identity primary key,
  year integer not null,
  agency text,
  subunit text,
  subcommittee text,
  account text,
  budget_number text,
  budget_function text,
  recipient text,
  amount numeric,
  location text,
  member text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create indexes for common query patterns
create index earmarks_year_idx on earmarks(year);
create index earmarks_location_idx on earmarks(location);
create index earmarks_agency_idx on earmarks(agency);
create index earmarks_member_idx on earmarks(member);

-- Enable full text search on recipient and budget function
create index earmarks_recipient_search_idx on earmarks using gin(to_tsvector('english', recipient));
create index earmarks_budget_function_search_idx on earmarks using gin(to_tsvector('english', budget_function)); 